name: Python Test

on: [push, pull_request]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.7'
    - name: Cache Pipenv virtualenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-v2-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-v2-
    - name: Install PyTorch
      run: |
        pip install pipenv
        export PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cpu
        pipenv run pip install torch
    - name: Install other dependencies
      run: |
        pipenv install --dev
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pipenv run python -m unittest discover
